In [1]:
!pip install simpletransformers

In [2]:
from simpletransformers.language_representation import RepresentationModel
from simpletransformers.config.model_args import ModelArgs

In [3]:
model_args = ModelArgs(max_seq_length=60)
model = RepresentationModel(
        model_type="bert",
        model_name="bert-base-uncased",
        args=model_args,
        use_cuda=False
    )

d:\projects\python projects\pythonproject-3.8\venv\lib\site-packages\cryptography\hazmat\backends\openssl\x509.py:14: CryptographyDeprecationWarning: This version of cryptography contains a temporary pyOpenSSL fallback path. Upgrade pyOpenSSL now.
  warnings.warn(
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForTextRepresentation: ['cls.predictions.transform.dense.bias', 'cls.predictions.decoder.weight', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.bias']
- This IS expected if you are initializing BertForTextRepresentation from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForTextRepresentation from the c

In [23]:
sentences = ["Machine Learning and Deep Learning are part of AI", "Machine Science will excel in future"]
word_vectors = model.encode_sentences(sentences, combine_strategy=None)

In [24]:
word_vectors.shape

(2, 11, 768)

In [21]:
word_vectors[0][0]

array([-2.31198862e-01,  2.60050058e-01, -2.77704209e-01, -4.72756863e-01,
       -5.46116829e-01, -8.41754898e-02,  7.36987293e-01,  2.38953590e-01,
       -2.30229020e-01, -6.44572377e-01, -4.34183002e-01, -2.77231336e-01,
        1.57358021e-01,  1.31324008e-01,  3.44409436e-01,  7.21418634e-02,
       -3.22926074e-01,  3.39355141e-01,  2.59710640e-01, -1.82778925e-01,
       -1.42284393e-01, -4.57956046e-01, -1.27952144e-01, -4.91912663e-01,
        1.40323266e-01,  4.26589131e-01,  4.59155887e-01, -1.98557109e-01,
       -4.15419079e-02,  3.32650691e-01,  3.63312244e-01,  8.39013875e-01,
       -1.76205665e-01,  3.42043310e-01,  1.63775459e-01, -1.97874486e-01,
        4.39825356e-01, -1.22933850e-01,  1.21041685e-01,  3.81555781e-02,
        2.45449230e-01, -6.75382018e-02, -3.00682008e-01, -1.37310609e-01,
       -2.66764998e-01, -4.06737447e-01, -2.71006560e+00, -2.64779449e-01,
       -7.67245889e-01,  1.65359288e-01, -1.77031577e-01, -4.69430536e-02,
        7.77960420e-02,  

In [22]:
word_vectors[1][0]

array([-1.74151003e-01,  1.65191829e-01,  7.08669871e-02, -1.26536250e-01,
       -5.24419725e-01, -4.65296984e-01,  7.58406937e-01,  4.19781476e-01,
        5.58057055e-02, -6.40085340e-01, -5.75481467e-02, -1.29128039e-01,
        2.27373287e-01,  1.10718459e-01,  1.74989939e-01, -2.51929402e-01,
        7.00067580e-02,  7.60246217e-01,  2.50760257e-01,  1.55406380e-02,
       -1.64421603e-01, -2.03809410e-01,  1.98861852e-01, -2.72453547e-01,
        1.60833761e-01, -3.21590900e-01, -6.32749870e-02,  7.35079721e-02,
        1.59409523e-01,  3.75192612e-03,  1.13246709e-01,  3.82177144e-01,
       -2.15118200e-01,  3.75558436e-01, -2.69987643e-01, -3.96449625e-01,
        2.56889910e-01,  1.07880428e-01,  2.91241288e-01,  3.26272488e-01,
        9.24477279e-02, -6.62169904e-02,  1.45073786e-01, -2.30864376e-01,
        9.50677544e-02, -9.75045383e-01, -2.64305806e+00, -3.74047607e-01,
        1.50467455e-03, -2.26082683e-01,  4.20607626e-01,  1.79404587e-01,
        1.78194433e-01,  

In [4]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [5]:
df = pd.read_csv("dataset/ask_play_station.csv")
df.dropna(inplace = True)
df

User  \
0      @AskPlayStation So, what's the november ps plu...   
1      @AskPlayStation It was when I would go to down...   
2      @AskPlayStation I bought Lego Star Wars in the...   
3      @AskPlayStation can i block a community from s...   
4        @AskPlayStation can you dm me I have a question   
...                                                  ...   
16711  @AskPlayStation I have already read and went o...   
16712  @AskPlayStation I can not fully connect to my ...   
16713  @AskPlayStation i want to buy a ps4 pro . will...   
16714  @AskPlayStation any idea when "Steven Universe...   
16715  @AskPlayStation May I ask what should I do if ...   

                                                 Company  
0      @115743 There is no info to share at the momen...  
1      @115745  Glad to know that is downloading, ple...  
2      @115745 Sorry for the inconvenience. Do you se...  
3      @115746  Glad to help.  Please share the detai...  
4      @116001 Glad to help! We have sent you a DM lo...  
...                                                  ...  
16711  @640122 Please run a network connection test. ...  
16712  @640122 Let's take a look! Check out the next ...  
16713  @823562 Hello there. There isn't information a...  
16714  @823563 Glad to help!  Please follow us via Tw...  
16715  @823570 Hello James! Please follow the steps i...  

[16701 rows x 2 columns]

In [14]:
avarage_size = df['Company'].apply(len).mean()
avarage_size

98.5778097119933

In [15]:
max = 0
for el in df['Company']:
    if(len(el) > max):
        max = len(el)
print(max)

275


In [7]:
df["User"] = df["User"].str.pad(max, side ='left')

In [8]:
len(df['User'][0])

365

In [10]:
train_data, test_data = train_test_split(df, test_size=0.3, random_state=42)

In [11]:
len(train_data)

11690

In [13]:
user_list = list(test_data['User'])
user_list[0]

'                                                                                                                                                                                                                                                                             @AmazonHelp Kindly make some arrangements where deliveries are combined and delivered at a time.'

In [12]:

word_vectors = model.encode_sentences(list(train_data['User']), combine_strategy=None, batch_size = 300)

In [13]:
word_vectors_company = model.encode_sentences(list(train_data['Company']), combine_strategy=None, batch_size = 300)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 44 and the array at index 1 has size 53

In [29]:
word_vectors.shape

(26250, 60, 768)

In [20]:
type(word_vectors)

numpy.ndarray

In [16]:
word_vectors

array([[[ 3.17125857e-01,  3.93123329e-02, -5.33362143e-02, ...,
         -5.41876912e-01,  3.46232921e-01,  5.41329503e-01],
        [ 1.44774449e+00, -7.05561116e-02,  1.90896079e-01, ...,
         -3.78027886e-01,  4.61026698e-01,  1.03290349e-01],
        [ 5.51739872e-01,  2.27829546e-01,  2.45805234e-01, ...,
         -2.92371184e-01,  1.68937296e-01,  1.91336796e-01],
        ...,
        [ 3.91529500e-02, -5.65730333e-01,  9.41301659e-02, ...,
          6.81319367e-03,  2.21679449e-01, -2.13752449e-01],
        [ 1.22146361e-01, -7.34543502e-01, -6.10550083e-02, ...,
          3.42473775e-01,  1.87422842e-01, -4.15363163e-01],
        [ 5.53031266e-01, -9.72811133e-02,  4.49494451e-01, ...,
          1.67237371e-02, -1.76964030e-02, -6.03395402e-02]],

       [[ 1.77624494e-01,  1.69677168e-01,  3.38462703e-02, ...,
         -3.32822323e-01,  1.76280454e-01,  3.09288472e-01],
        [ 6.40296340e-01, -4.08758223e-02,  5.41484237e-01, ...,
         -5.19902349e-01, -2.31951177e

In [99]:
word_vectors[0].shape

(83, 768)